//AUTHENTICATE
export const LOGINUSERSUCCESS = "LOGINUSERSUCCESS";
export const LOGINUSERFAILED = "LOGINUSERFAILED";
export const LOGOUTUSER = "LOGOUTUSER";

//CHAT
export const SETCHATID = 'SETCHATID';
export const CHATLOADINGFAILED = "CHATLOADINGFAILED"; 